## Program Perhitungan Manual Backpropagation

### Import Library

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
import pandas as pd

### Fungsi Sigmoid

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

### Fungsi Normalisasi Dataset

In [ ]:
def normalize(X):
    X_min = np.min(X)
    X_max = np.max(X)

    return (0.8 * (X - X_min)) / (X_max - X_min) + 0.1

### Fungsi Hitung Rataan Error Epoch

In [ ]:
def mse(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

### Fungsi Backpropagation

In [ ]:
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size, learning_rate=0.1):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.learning_rate = learning_rate

        self.W = np.array(
       [[0.0428927628551653, 0.655118395300202, 0.746573398966137 ],
        [0.807370624407692, 0.897255338348159, 0.387199186198249],
        [0.532026205396165, 0.688253994121348, 0.334018649961921],
        [0.153752040107356, 0.936037943051975, 0.068689648607059],
        [0.309703428895647, 0.700240004767994, 0.781739193770057],
        [0.406991451687261, 0.189983103141083, 0.467545492326857],
        [0.954662459934756, 0.343284615699016, 0.891342996489653],
        [0.162170045154412, 0.810361913458311, 0.351013620518371],
        [0.6229046299264063, 0.689000284059038, 0.373639547475893],
        [0.112281030480022, 0.0475671240101184,0.321643835692924],
        [0.5798257516678, 0.652191836846907, 0.204259339021227],
        [0.95737762066294, 0.778240667534575, 0.793272283030633],
        [0.876109589643017, 0.983141475361845, 0.213960887224048]])

        self.V = np.array([[0.798131247118299], [0.250628532833808], [0.0964996656169769]])
        self.b_hidden = np.array([[0.0912129025693111, 0.30825367914119, 0.507012029988612]])
        self.b_output = np.array([[0.925404827205998]])

    def forward(self, X):
        self.hidden_net = np.dot(X, self.W) + self.b_hidden
        self.hidden_output = sigmoid(self.hidden_net)

        self.output_net = np.dot(self.hidden_output, self.V) + self.b_output
        self.output = sigmoid(self.output_net)

        return self.output

    def backward(self, X, y):
      output_error = y - self.output
      self.delta_output = output_error * sigmoid_derivative(self.output)

      self.delta_hidden = np.dot(self.delta_output, self.V.T) * sigmoid_derivative(self.hidden_output)

      self.V += self.learning_rate * np.dot(self.hidden_output.T, self.delta_output)
      self.W += self.learning_rate * np.dot(X.T, self.delta_hidden)

      self.b_output += self.learning_rate * np.sum(self.delta_output, axis=0)
      self.b_hidden += self.learning_rate * np.sum(self.delta_hidden, axis=0)


    def train(self, X, y, epochs=50):
        for epoch in range(1, epochs + 1):
            self.forward(X)
            self.backward(X, y)
            if epoch % 10 == 0:
                loss = mse(y, self.output)
                print(f'Epoch {epoch}, Mean Squared Error: {loss}')
                # print(f'Epoch {epoch}, Network Output: \n{self.output}')

        print("\nBobot Input - Hidden Akhir:\n", self.W)
        print("\nBobot Hidden - Output Akhir:\n", self.V)
        print("\nBobot Bias Hidden Akhir:\n", self.b_hidden)
        print("\nBobot Bias Output Akhir:\n", self.b_output)

### Fungsi Latih

In [ ]:
input_data = np.array([
    [57, 1, 2, 124, 261, 0, 0, 141, 0, 0.3, 1, 0, 7],
    [64, 1, 4, 128, 263, 0, 0, 105, 1, 0.2, 2, 1, 7],
    [74, 0, 2, 120, 269, 0, 2, 121, 1, 0.2, 1, 1, 3],
    [65, 1, 4, 120, 177, 0, 0, 140, 0, 0.4, 1, 0, 7],
    [56, 1, 3, 130, 256, 1, 2, 142, 1, 0.6, 2, 1, 6],
    [59, 1, 4, 110, 239, 0, 2, 142, 1, 1.2, 2, 1, 7]
])

target = np.array([1, 0, 0, 0, 1, 1])

X_min = input_data.min(axis=0)
X_max = input_data.max(axis=0)
normalized_input = normalize(input_data)


input_size = input_data.shape[1]
hidden_size = 3
output_size = 1

nn = NeuralNetwork(input_size=input_size, hidden_size=hidden_size, output_size=output_size, learning_rate=0.1)
nn.train(normalized_input, target.reshape(-1, 1), epochs=50)

Epoch 10, Mean Squared Error: 0.3065367008960291
Epoch 20, Mean Squared Error: 0.2578132864383273
Epoch 30, Mean Squared Error: 0.2507943184788383
Epoch 40, Mean Squared Error: 0.250193594339773
Epoch 50, Mean Squared Error: 0.25014277027029214

Bobot Input - Hidden Akhir:
 [[0.01895965 0.65611404 0.75124276]
 [0.80061201 0.89736708 0.38823766]
 [0.52449629 0.68841598 0.33524136]
 [0.12195789 0.93672388 0.07382057]
 [0.26145304 0.70019186 0.78746309]
 [0.40036784 0.19009174 0.46855928]
 [0.94802685 0.34337243 0.89231974]
 [0.13780184 0.80981312 0.35320133]
 [0.61603415 0.689129   0.37471621]
 [0.1056392  0.04766998 0.32265154]
 [0.57293728 0.65230417 0.20531251]
 [0.95050714 0.77836939 0.79434895]
 [0.8685786  0.98323498 0.21507182]]

Bobot Hidden - Output Akhir:
 [[ 0.37819166]
 [-0.27510205]
 [-0.4052432 ]]

Bobot Bias Hidden Akhir:
 [[0.02380669 0.30953503 0.5176317 ]]

Bobot Bias Output Akhir:
 [[0.34654961]]


### Fungsi Testing

In [ ]:
test_input = np.array([
    [58, 0, 1, 136, 319, 1, 0, 152, 0, 0, 2, 2, 2],
    [61, 1, 0, 138, 166, 0, 0, 125, 1, 36, 1, 1, 2],
    [42, 1, 0, 136, 315, 0, 1, 125, 1, 18, 1, 0, 1],
    [64, 1, 3, 110, 211, 0, 0, 144, 1, 18, 1, 0, 2],
    [58, 0, 3, 150, 283, 1, 0, 162, 0, 10, 2, 0, 2],
    [50, 0, 2, 120, 219, 0, 1, 158, 0, 16, 1, 0, 2]
])

test_target = np.array([0, 0, 0, 1, 1, 1]).reshape(-1, 1)

normalized_test_input = (0.8 * (test_input - X_min)) / (X_max - X_min) + 0.1

predictions = nn.forward(normalized_test_input)

binary_predictions = (predictions >= 0.3).astype(int)


print("Predicted Outputs:")
for i, prediction in enumerate(predictions, 1):
    print(f"Sample {i}: {prediction[0]:.6f} (Hasil Prediksi: {binary_predictions[i-1][0]})")

# Calculate metrics
accuracy = accuracy_score(test_target, binary_predictions)
precision = precision_score(test_target, binary_predictions)
recall = recall_score(test_target, binary_predictions)
f1 = f1_score(test_target, binary_predictions)

# Print metrics
print("\nEvaluation Metrics:")
print(f"Accuracy: {accuracy:.6f}")
print(f"Precision: {precision:.6f}")
print(f"Recall: {recall:.6f}")
print(f"F1 Score: {f1:.6f}")


Predicted Outputs:
Sample 1: 0.509083 (Hasil Prediksi: 1)
Sample 2: 0.510960 (Hasil Prediksi: 1)
Sample 3: 0.509303 (Hasil Prediksi: 1)
Sample 4: 0.509406 (Hasil Prediksi: 1)
Sample 5: 0.506854 (Hasil Prediksi: 1)
Sample 6: 0.507174 (Hasil Prediksi: 1)

Evaluation Metrics:
Accuracy: 0.500000
Precision: 0.500000
Recall: 1.000000
F1 Score: 0.666667


## Program Perhitungan Backpropagation Dengan Dataset

In [ ]:
data = pd.read_csv('cleaned_merged_heart_dataset.csv')
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalachh  exang  oldpeak  \
0   63    1   3       145   233    1        0       150      0      2.3   
1   37    1   2       130   250    0        1       187      0      3.5   
2   41    0   1       130   204    0        0       172      0      1.4   
3   56    1   1       120   236    0        1       178      0      0.8   
4   57    0   0       120   354    0        1       163      1      0.6   

   slope  ca  thal  target  
0      0   0     1       1  
1      0   0     2       1  
2      2   0     2       1  
3      2   0     2       1  
4      2   0     2       1

In [ ]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train_normalized = normalize(X_train)
X_test_normalized = normalize(X_test)

In [ ]:
input_size = X.shape[1]
hidden_size = 3
output_size = 1

nn = NeuralNetwork(input_size, hidden_size, output_size, learning_rate=0.01)
nn.train(X_train_normalized, y_train.reshape(-1, 1), epochs=1000)

Epoch 10, Mean Squared Error: 0.2854175859657047
Epoch 20, Mean Squared Error: 0.2734838811829249
Epoch 30, Mean Squared Error: 0.2616072784392381
Epoch 40, Mean Squared Error: 0.2545776041473314
Epoch 50, Mean Squared Error: 0.25143427743815616
Epoch 60, Mean Squared Error: 0.25019260781847524
Epoch 70, Mean Squared Error: 0.24972011158545335
Epoch 80, Mean Squared Error: 0.2495371114665417
Epoch 90, Mean Squared Error: 0.24946016712310146
Epoch 100, Mean Squared Error: 0.2494214335889743
Epoch 110, Mean Squared Error: 0.2493959410813247
Epoch 120, Mean Squared Error: 0.2493743891816306
Epoch 130, Mean Squared Error: 0.249353200370605
Epoch 140, Mean Squared Error: 0.24933089524717209
Epoch 150, Mean Squared Error: 0.24930676353930856
Epoch 160, Mean Squared Error: 0.24928037100963002
Epoch 170, Mean Squared Error: 0.24925137311154863
Epoch 180, Mean Squared Error: 0.24921944240528587
Epoch 190, Mean Squared Error: 0.24918423865195
Epoch 200, Mean Squared Error: 0.24914539509267072
Ep

In [ ]:
predictions_test = nn.forward(X_test_normalized)
hasil_test = (predictions_test >= 0.3).astype(int)

accuracy_test = accuracy_score(y_test, hasil_test)
precision_test = precision_score(y_test, hasil_test)
recall_test = recall_score(y_test, hasil_test)
f1_test = f1_score(y_test, hasil_test)

print("Test Confusion Matrix:")
print(f"Accuracy: {accuracy_test:.4f}")
print(f"Precision: {precision_test:.4f}")
print(f"Recall: {recall_test:.4f}")
print(f"F1 Score: {f1_test:.4f}")


Test Confusion Matrix:
Accuracy: 0.5026
Precision: 0.5026
Recall: 1.0000
F1 Score: 0.6690
